(() => {
  const APPS_SCRIPT_URL='https://script.google.com/macros/s/AKfycbyTFbn9riBXqN7zxocqEmYUDhE8IlQJvU3QGBIRvbXgobN6IsXo_PcU76IkP32eEDJGlw/exec';
  const SUPABASE_URL='https://aovespfbrgctyxhxssji.supabase.co';
  const SUPABASE_KEY='sb_publishable_konWtcjta3QLKDoRgUao9Q_YmSEBi2a';
  const ALLOWED=new Set(['msindisi.mtengwane@gmail.com','nomondehlonyane@gmail.com']);
  const client=window.supabase?.createClient?window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY):null;
  const tenantId=new URLSearchParams(location.search).get('tenantId')||'';
  let lease=null,accessToken='';
  const status=document.getElementById('leaseAdminStatus');
  const actionStatus=document.getElementById('adminLeaseActionStatus');
  const signButton=document.getElementById('signLease');
  const canvas=document.getElementById('landlordCanvas'),ctx=canvas.getContext('2d');ctx.strokeStyle='#13293d';ctx.lineWidth=2.4;ctx.lineCap='round';let drawing=false;
  function point(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*canvas.width/r.width,y:(e.clientY-r.top)*canvas.height/r.height}}
  canvas.addEventListener('pointerdown',e=>{drawing=true;const p=point(e);ctx.beginPath();ctx.moveTo(p.x,p.y);e.preventDefault()});canvas.addEventListener('pointermove',e=>{if(!drawing)return;const p=point(e);ctx.lineTo(p.x,p.y);ctx.stroke();e.preventDefault()});window.addEventListener('pointerup',()=>drawing=false);document.getElementById('clearLandlordSignature').onclick=()=>ctx.clearRect(0,0,canvas.width,canvas.height);
  function compressedSignature(){const small=document.createElement('canvas');small.width=350;small.height=95;small.getContext('2d').drawImage(canvas,0,0,350,95);return small.toDataURL('image/png')}
  function drawSignature(data){if(!data)return;const img=new Image();img.onload=()=>{ctx.clearRect(0,0,canvas.width,canvas.height);ctx.drawImage(img,0,0,canvas.width,canvas.height)};img.src=data}
  function jsonp(params){return new Promise((resolve,reject)=>{const cb='hlonyaneAdminLeaseReview_'+Date.now()+'_'+Math.random().toString(36).slice(2);const s=document.createElement('script');const t=setTimeout(()=>{cleanup();reject(new Error('Lease service timed out.'))},10000);function cleanup(){clearTimeout(t);delete window[cb];s.remove()}window[cb]=data=>{cleanup();resolve(data)};s.src=APPS_SCRIPT_URL+'?'+new URLSearchParams({...params,callback:cb,_:Date.now().toString()});s.onerror=()=>{cleanup();reject(new Error('Unable to reach lease service.'))};document.head.append(s)})}
  async function post(action,payload){await fetch(APPS_SCRIPT_URL,{method:'POST',mode:'no-cors',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action,accessToken,...payload})})}
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function render(){if(!lease)return;const d=lease.form||{};document.getElementById('leaseHeading').textContent=`Lease · ${lease.tenantName||lease.tenantEmail}`;document.getElementById('leaseStatusPill').textContent=lease.status||'Not started';const fields=[['Tenant',d.tenantName||lease.tenantName],['ID / Passport',d.tenantId||'—'],['Email',d.tenantEmail||lease.tenantEmail],['Mobile',d.tenantMobile||'—'],['Residential address',d.tenantAddress||'—'],['Premises',d.propertyAddress||lease.property],['Monthly rent',d.rent?`R${d.rent}`:'—'],['Deposit',d.deposit?`R${d.deposit}`:'—'],['Lease start',d.startDate||'—'],['Lease end',d.endDate||'—'],['Occupants',d.occupants||'—'],['Parking / carport',d.parking||'—']];document.getElementById('leaseSummary').innerHTML=fields.map(([a,b])=>`<div class="lease-summary-field"><span>${esc(a)}</span><strong>${esc(b)}</strong></div>`).join('');document.getElementById('tenantTypedSignature').textContent=d.typedSignature||lease.tenantName||'Tenant signature';const ti=document.getElementById('tenantSignatureImage');if(lease.tenantSignature){ti.src=lease.tenantSignature;ti.hidden=false}else ti.hidden=true;document.getElementById('tenantSignedAt').textContent=lease.tenantSignedAt?`Tenant signed: ${new Date(lease.tenantSignedAt).toLocaleString('en-ZA')}`:'Tenant has not signed yet.';if(lease.landlordSignature)drawSignature(lease.landlordSignature);const landlordName=String(d.landlordSignature||lease.landlordSignedBy||'').trim();if(landlordName)document.getElementById('landlordTypedSignature').value=landlordName;
    if(lease.status==='Fully signed'){status.className='lease-admin-status done';status.textContent='Lease complete. Tenant and landlord signatures are both recorded.';signButton.disabled=true;signButton.textContent='Fully signed';document.getElementById('landlordTypedSignature').disabled=true;canvas.style.pointerEvents='none';document.getElementById('clearLandlordSignature').disabled=true;actionStatus.textContent=`Landlord signed ${lease.landlordSignedAt?new Date(lease.landlordSignedAt).toLocaleString('en-ZA'):''}.`}
    else if(lease.status==='Tenant signed'){status.className='lease-admin-status';status.textContent='Tenant has signed. Review the shared lease below and add the landlord signature.';signButton.disabled=false}
    else{status.className='lease-admin-status warn';status.textContent='The tenant has not signed this lease yet. The landlord signature is locked until the tenant signs.';signButton.disabled=true;canvas.style.pointerEvents='none';document.getElementById('landlordTypedSignature').disabled=true;document.getElementById('clearLandlordSignature').disabled=true}
  }
  async function load(){if(!tenantId)throw new Error('Tenant ID is missing.');const r=await jsonp({action:'admin.getLease',tenantId,accessToken});if(r?.ok===false)throw new Error(r.error);lease=r.lease;render()}
  async function init(){if(!client){location.replace('admin.html');return}const {data:{session}}=await client.auth.getSession();const email=String(session?.user?.email||'').toLowerCase();if(!session?.access_token||!ALLOWED.has(email)){location.replace('admin.html?error=unauthorised');return}accessToken=session.access_token;try{await load()}catch(e){status.className='lease-admin-status warn';status.textContent=e.message||'Unable to load lease.';signButton.disabled=true}}
  signButton.onclick=async()=>{if(!lease||lease.status!=='Tenant signed')return;const typed=document.getElementById('landlordTypedSignature').value.trim();if(!typed){document.getElementById('landlordTypedSignature').focus();return}signButton.disabled=true;signButton.textContent='Signing…';actionStatus.textContent='Saving landlord signature to the shared lease…';try{const formData={...(lease.form||{}),landlordSignature:typed,landlordSignedAtPlace:document.getElementById('landlordSignedAtPlace').value.trim()};await post('admin.signLease',{tenantId,form:formData,landlordName:typed,landlordSignature:compressedSignature()});setTimeout(async()=>{await load();signButton.textContent='Fully signed';actionStatus.textContent='Lease completed and locked.'},900)}catch(e){signButton.disabled=false;signButton.textContent='Sign lease as landlord';actionStatus.textContent=e.message||'Unable to sign lease.'}}
  document.getElementById('printLease').onclick=()=>window.print();
  init();
})();
