const properties = window.SITE_OVERRIDES && Array.isArray(window.SITE_OVERRIDES.properties) ? window.SITE_OVERRIDES.properties : [
  {name:'New Flats',address:'4 Van Reenen Street',city:'Middelburg EC',count:7,vacant:2,vacancySample:true,beds:2,baths:1,area:70,rent:6000,furnished:9000,type:'2-bedroom apartments',photoGroup:'new',heroNumber:80,excludeNumbers:[100,101,102,103,104,105,106,107,108,109]},
  {name:'New Flats',address:'4 Van Reenen Street',city:'Middelburg EC',count:17,vacant:4,vacancySample:true,beds:1,baths:1,area:49,rent:4500,furnished:6000,type:'1-bedroom / bachelor apartments',photoGroup:'new',heroNumber:60,excludeNumbers:[76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99]},
  {name:'21 Roode Street',address:'21 Roode Street',city:'Middelburg EC',count:1,vacant:0,vacancySample:true,beds:4,baths:2,area:null,rent:null,furnished:null,type:'4-bedroom house',photoGroup:'roode-2bed-furnished',heroNumber:11,excludeNumbers:[]},
  {name:'21 Roode Street',address:'21 Roode Street',city:'Middelburg EC',count:null,vacant:null,beds:2,baths:null,area:null,rent:6000,furnished:9000,type:'2-bedroom apartments',photoGroup:'roode-2bed-furnished',heroNumber:11,excludeNumbers:[]},
  {name:'21 Roode Street',address:'21 Roode Street',city:'Middelburg EC',count:10,vacant:3,vacancySample:true,beds:1,baths:1,area:49,rent:4500,furnished:6000,type:'1-bedroom apartments',photoGroup:'roode',heroNumber:45,excludeNumbers:[11,12,13,14,15,16,17,18,19,20,21]}
];
properties.forEach((property,index)=>{property._index=index;property.excludeNumbers=property.excludeNumbers||[]});
const money=n=>'R '+n.toString().replace(/\B(?=(\d{3})+(?!\d))/g,' ');const $=s=>document.querySelector(s);
function matchingProperties(query,bedrooms,budget){return properties.filter(p=>(p.name+' '+p.address+' '+p.city).toLowerCase().includes(query.trim().toLowerCase())&&(!bedrooms||p.beds===bedrooms)&&(p.rent===null||p.rent<=budget))}
function vacancyLabel(p){if(!Number.isInteger(p.vacant)||p.vacant<0||p.vacant>p.count)return 'Availability: please enquire';return 'Available: '+p.vacant}
function photoLabel(photo,p){if(photo.categories.some(category=>category.endsWith('-furnished')&&!category.endsWith('-unfurnished')))return 'Furnished';if(photo.categories.some(category=>category.endsWith('-unfurnished')))return 'Unfurnished';return p.name==='New Flats'?'New Flats':'Roode Flats'}
function propertyHeroMarkup(p){let custom=window.SITE_OVERRIDES&&window.SITE_OVERRIDES.propertyPhotos&&window.SITE_OVERRIDES.propertyPhotos[p._index];let photos=Array.isArray(custom)&&custom.length?custom:(window.PROPERTY_GALLERY||[]).filter(photo=>photo.orientation==='landscape'&&photo.categories.includes(p.photoGroup)&&!p.excludeNumbers.includes(photo.number));photos=photos.map((photo,i)=>typeof photo==='string'?{image:photo,caption:`${p.name} photograph ${i+1}`,categories:[]} : photo);photos.sort((a,b)=>(a.number||0)-(b.number||0));const featured=photos.findIndex(photo=>photo.number===p.heroNumber);if(featured>0)photos.unshift(photos.splice(featured,1)[0]);if(!photos.length)return '';return `<div class="property-hero" data-property-carousel aria-label="${p.name} ${p.type} photo slideshow">${photos.map((photo,index)=>`<figure class="property-hero-slide" data-property-slide ${index===0?'':'hidden'}><img src="${photo.image}" alt="${photo.caption||p.name+' photograph'}" ${index===0?'fetchpriority="high"':'loading="lazy"'} decoding="async"><figcaption>${photoLabel(photo,p)}</figcaption></figure>`).join('')}${photos.length>1?`<div class="property-hero-controls"><button type="button" data-property-prev aria-label="Previous ${p.name} photograph">←</button><span data-property-count></span><button type="button" data-property-next aria-label="Next ${p.name} photograph">→</button></div>`:''}</div>`}
function initPropertyCarousels(){document.querySelectorAll('[data-property-carousel]').forEach(carousel=>{const slides=[...carousel.querySelectorAll('[data-property-slide]')];if(slides.length<2)return;let index=0;const count=carousel.querySelector('[data-property-count]');const show=next=>{index=(next+slides.length)%slides.length;slides.forEach((slide,i)=>{slide.hidden=i!==index});count.textContent=`${index+1} / ${slides.length}`};carousel.querySelector('[data-property-prev]').addEventListener('click',()=>show(index-1));carousel.querySelector('[data-property-next]').addEventListener('click',()=>show(index+1));show(0)})}
function render(){const rows=matchingProperties($('#search').value,+$('#beds').value,+$('#rent').value);$('#rentOutput').textContent=money(+$('#rent').value);$('#propertyGrid').innerHTML=rows.length?rows.map(p=>`<article class="property-card">${propertyHeroMarkup(p)}<div class="property-copy"><div class="location">Middelburg · Eastern Cape</div><h3>${p.name}</h3>${p.name!==p.address?`<p class="property-address">${p.address}</p>`:''}<p class="apartment-type">${p.type}</p>${Number.isInteger(p.count)?`<p class="unit-count">${p.count} apartments</p>`:''}<p class="vacancy-status">${vacancyLabel(p)}</p><div class="meta">${p.beds} bedroom${p.beds===1?'':'s'}${p.baths?` · ${p.baths} bathroom`:''}${p.area?` · ${p.area} m²`:''}</div>${Number.isFinite(p.rent)&&Number.isFinite(p.furnished)?`<table class="rate-table"><caption>Monthly rental</caption><tbody><tr><th scope="row">Unfurnished</th><td>${money(p.rent)}</td></tr><tr><th scope="row">Furnished</th><td>${money(p.furnished)}</td></tr></tbody></table>`:'<p class="rate-enquiry">Please enquire for current availability and rental rates.</p>'}<a class="button button-dark" href="#contact" data-enquiry="${p.address} — ${p.type}">Enquire about this apartment ↗</a></div></article>`).join(''):'<p class="no-properties">No apartments match these filters. Try another address, bedroom selection or a higher monthly budget.</p>';$('#propertyGrid').scrollLeft=0;initPropertyCarousels()}
$('#propertyPrev').addEventListener('click',()=>pageProperties(-1));$('#propertyNext').addEventListener('click',()=>pageProperties(1));function pageProperties(direction){const grid=$('#propertyGrid'),card=grid.querySelector('.property-card');if(!card)return;const gap=parseFloat(getComputedStyle(grid).gap)||20;grid.scrollBy({left:direction*(card.getBoundingClientRect().width+gap),behavior:'smooth'});}
['search','beds','rent'].forEach(id=>$('#'+id).addEventListener('input',render));document.addEventListener('click',event=>{const link=event.target.closest('[data-enquiry]');if(!link)return;setEnquiry(link.dataset.enquiry);const message=document.querySelector('#enquiryForm textarea[name="message"]');if(message)message.value='I would like to enquire about '+link.dataset.enquiry+'.'});render();
document.querySelector('.menu-toggle').addEventListener('click',e=>{const nav=document.querySelector('.site-nav'),open=nav.classList.toggle('open');e.currentTarget.setAttribute('aria-expanded',open)});document.querySelectorAll('.site-nav a').forEach(a=>a.addEventListener('click',()=>document.querySelector('.site-nav').classList.remove('open')));$('#newRequest').addEventListener('click',()=>$('#repairDialog').showModal());$('#repairForm').addEventListener('submit',e=>{if(e.submitter.value==='cancel')return;const data=new FormData(e.currentTarget),n=+$('#requestCount').textContent+1;$('#requestCount').textContent=n;$('#requestList').insertAdjacentHTML('afterbegin',`<div class="request-item"><strong>DEMO-${String(n).padStart(3,'0')} · ${data.get('category')}</strong><br>${data.get('description')}<br><small>Submitted · Demo session</small></div>`)});$('#enquiryForm').addEventListener('submit',e=>{e.preventDefault();$('#formStatus').textContent='✓ Form validated. No message was sent — this is a preview.'});function setEnquiry(name){$('#formStatus').textContent='Selected property: '+name};$('#year').textContent=new Date().getFullYear();
