const form=document.getElementById('leaseForm');
form.signedDate.value=new Date().toISOString().slice(0,10);
const pads={};
function setupCanvas(id){const c=document.getElementById(id),ctx=c.getContext('2d');ctx.strokeStyle='#13293d';ctx.lineWidth=2.4;ctx.lineCap='round';let drawing=false;function point(e){const r=c.getBoundingClientRect();return{x:(e.clientX-r.left)*c.width/r.width,y:(e.clientY-r.top)*c.height/r.height}}c.addEventListener('pointerdown',e=>{drawing=true;const p=point(e);ctx.beginPath();ctx.moveTo(p.x,p.y);e.preventDefault()});c.addEventListener('pointermove',e=>{if(!drawing)return;const p=point(e);ctx.lineTo(p.x,p.y);ctx.stroke();e.preventDefault()});window.addEventListener('pointerup',()=>drawing=false);pads[id]=ctx}setupCanvas('tenantCanvas');setupCanvas('landlordCanvas');
document.querySelectorAll('[data-clear]').forEach(b=>b.addEventListener('click',()=>{const c=document.getElementById(b.dataset.clear);pads[b.dataset.clear].clearRect(0,0,c.width,c.height)}));
function save(){const data=Object.fromEntries(new FormData(form).entries());data.tenantSignature=document.getElementById('tenantCanvas').toDataURL();data.landlordSignature=document.getElementById('landlordCanvas').toDataURL();localStorage.setItem('hlonyaneLeaseDraft',JSON.stringify(data));document.getElementById('saveStatus').textContent='Draft saved just now in this browser.'}
document.getElementById('saveDraft').addEventListener('click',save);form.addEventListener('input',()=>{clearTimeout(window.leaseTimer);window.leaseTimer=setTimeout(save,700)});
document.getElementById('downloadLease').addEventListener('click',()=>{if(!form.reportValidity())return;save();const d=Object.fromEntries(new FormData(form).entries());const lines=['HLONYANE’S RESIDENTIAL — COMPLETED LEASE DRAFT','',`Tenant: ${d.tenantName}`,`ID / Passport: ${d.tenantId}`,`Email: ${d.tenantEmail}`,`Mobile: ${d.tenantMobile}`,`Address: ${d.tenantAddress}`,`Premises: ${d.propertyAddress}`,`Monthly rent: R${d.rent}`,`Deposit: R${d.deposit}`,`Lease period: ${d.startDate} to ${d.endDate}`,`Occupants: ${d.occupants}`,`Parking / carport: ${d.parking||'None recorded'}`,'','The tenant confirms that the standard Hlonyane’s Residential lease terms were read and accepted.','',`Tenant typed signature: ${d.typedSignature||'Signed by drawing on screen'}`,`Landlord typed signature: ${d.landlordSignature||'Pending landlord signature'}`,`Signed at: ${d.signedAt}`,`Date: ${d.signedDate}`,'','The final executed agreement should be stored by the property manager.'];const blob=new Blob([lines.join('\n')],{type:'text/plain'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='hlonyane-lease-completed-draft.txt';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)});
const printButton=document.createElement('button');printButton.type='button';printButton.className='outline-btn';printButton.textContent='Print / save as PDF';document.querySelector('.lease-actions').insertBefore(printButton,document.getElementById('downloadLease'));printButton.addEventListener('click',()=>{if(!form.reportValidity())return;save();const d=Object.fromEntries(new FormData(form).entries());const tenantSig=document.getElementById('tenantCanvas').toDataURL();const landlordSig=document.getElementById('landlordCanvas').toDataURL();const w=window.open('','_blank');w.document.write(`<html><head><title>Hlonyane Residential lease agreement</title><style>body{font:14px Arial;color:#13293d;max-width:800px;margin:35px auto;line-height:1.5}h1{font-size:26px;border-bottom:2px solid #b98516;padding-bottom:12px}h2{font-size:17px;margin-top:24px;color:#b98516}.grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.field{border-bottom:1px solid #ccd6da;padding:8px 0}.field b{display:block;font-size:11px;color:#748088}.terms{border-top:1px solid #ddd;margin-top:15px;padding-top:12px}.sig{width:280px;border-bottom:1px solid #13293d;margin-top:10px}.sig img{width:280px;height:76px;object-fit:contain;object-position:left bottom}</style></head><body><h1>Hlonyane’s Residential — Lease Agreement</h1><div class="grid"><div class="field"><b>Tenant</b>${d.tenantName}</div><div class="field"><b>ID / Passport</b>${d.tenantId}</div><div class="field"><b>Email</b>${d.tenantEmail}</div><div class="field"><b>Mobile</b>${d.tenantMobile}</div><div class="field"><b>Premises</b>${d.propertyAddress}</div><div class="field"><b>Monthly rent</b>R${d.rent}</div><div class="field"><b>Deposit</b>R${d.deposit}</div><div class="field"><b>Lease period</b>${d.startDate} to ${d.endDate}</div></div><h2>Acceptance</h2><p>The tenant confirms that the standard Hlonyane’s Residential lease terms were read and accepted.</p><h2>Signatures</h2><div class="grid"><div class="sig"><b>Tenant</b><br>${d.typedSignature||''}<img src="${tenantSig}"></div><div class="sig"><b>Landlord</b><br>${d.landlordSignature||''}<img src="${landlordSig}"></div></div><p>Signed at ${d.signedAt} on ${d.signedDate}</p><script>window.onload=()=>window.print()<\/script></body></html>`);w.document.close()});
// Browser-local handoff until the connected admin portal and Resend delivery are enabled.
function portalState(){try{return JSON.parse(localStorage.getItem('hlonyaneTenantPortalV42')||'{}')}catch(e){return {}}}
function savePortalLease(status){const d=Object.fromEntries(new FormData(form).entries());d.tenantSignature=document.getElementById('tenantCanvas').toDataURL();d.landlordSignature=document.getElementById('landlordCanvas').toDataURL();d.status=status;d.savedAt=new Date().toISOString();const portal=portalState();portal.lease=d;localStorage.setItem('hlonyaneTenantPortalV42',JSON.stringify(portal));localStorage.setItem('hlonyaneLeaseDraft',JSON.stringify(d));document.getElementById('saveStatus').textContent=status==='Pending landlord signature'?'Submitted to the admin portal. Awaiting landlord signature.':'Lease copy saved in this browser.'}
document.getElementById('saveDraft').addEventListener('click',()=>savePortalLease('Draft saved'));
const submit=document.createElement('button');submit.type='button';submit.className='gold-btn';submit.textContent='Submit to admin portal';document.querySelector('.lease-actions').appendChild(submit);submit.addEventListener('click',()=>{if(!form.reportValidity())return;savePortalLease('Pending landlord signature')});
