const form=document.getElementById('leaseForm');
const APPS_SCRIPT_URL='https://script.google.com/macros/s/AKfycbyTFbn9riBXqN7zxocqEmYUDhE8IlQJvU3QGBIRvbXgobN6IsXo_PcU76IkP32eEDJGlw/exec';
const readJSON=(key,fallback={})=>{try{return JSON.parse(localStorage.getItem(key)||'null')??fallback}catch(e){return fallback}};
const tenantSession=readJSON('hlonyaneTenantSession',{});
const portalStateAtLoad=readJSON('hlonyaneTenantPortalV42',{});
const statusEl=document.getElementById('saveStatus');
let remoteLease=null;

function jsonp(params){return new Promise((resolve,reject)=>{const cb='hlonyaneLease_'+Date.now()+'_'+Math.random().toString(36).slice(2);const s=document.createElement('script');const timer=setTimeout(()=>{cleanup();reject(new Error('Lease service timed out.'))},10000);function cleanup(){clearTimeout(timer);delete window[cb];s.remove()}window[cb]=data=>{cleanup();resolve(data)};s.src=APPS_SCRIPT_URL+'?'+new URLSearchParams({...params,callback:cb,_:Date.now().toString()});s.onerror=()=>{cleanup();reject(new Error('Unable to reach the lease service.'))};document.head.append(s)})}
async function postLease(action,payload){await fetch(APPS_SCRIPT_URL,{method:'POST',mode:'no-cors',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action,email:tenantSession.email,tenantId:tenantSession.tenantId||tenantSession.id,...payload})})}
function setField(name,value){const f=form.elements[name];if(!f||value==null||value==='')return;if(f.type==='checkbox')f.checked=!!value;else f.value=value}
function formDataObject(){const d=Object.fromEntries(new FormData(form).entries());d.termsAccepted=!!form.elements.termsAccepted?.checked;return d}
function prefillTenantDetails(){setField('tenantName',tenantSession.name||portalStateAtLoad?.profile?.name||'');setField('tenantEmail',tenantSession.email||portalStateAtLoad?.profile?.email||'');setField('tenantMobile',tenantSession.mobile||portalStateAtLoad?.profile?.mobile||'');setField('propertyAddress',tenantSession.property||'');const rent=String(tenantSession.rent||'').replace(/[^0-9.]/g,'');if(rent)setField('rent',rent);const dep=String(tenantSession.deposit||'').replace(/[^0-9.]/g,'');if(dep)setField('deposit',dep);if(tenantSession.leaseStart)setField('startDate',String(tenantSession.leaseStart).slice(0,10));if(tenantSession.leaseEnd)setField('endDate',String(tenantSession.leaseEnd).slice(0,10));if(form.elements.signedDate&&!form.elements.signedDate.value)form.elements.signedDate.value=new Date().toISOString().slice(0,10)}
prefillTenantDetails();

const pads={};
function setupCanvas(id,enabled=true){const c=document.getElementById(id),ctx=c.getContext('2d');ctx.strokeStyle='#13293d';ctx.lineWidth=2.4;ctx.lineCap='round';let drawing=false;function point(e){const r=c.getBoundingClientRect();return{x:(e.clientX-r.left)*c.width/r.width,y:(e.clientY-r.top)*c.height/r.height}}if(enabled){c.addEventListener('pointerdown',e=>{drawing=true;const p=point(e);ctx.beginPath();ctx.moveTo(p.x,p.y);e.preventDefault()});c.addEventListener('pointermove',e=>{if(!drawing)return;const p=point(e);ctx.lineTo(p.x,p.y);ctx.stroke();e.preventDefault()});window.addEventListener('pointerup',()=>drawing=false)}else{c.style.pointerEvents='none';c.style.background='#f4f6f5'}pads[id]=ctx}
setupCanvas('tenantCanvas',true);setupCanvas('landlordCanvas',false);
document.querySelectorAll('[data-clear]').forEach(b=>{if(b.dataset.clear==='landlordCanvas'){b.hidden=true;return}b.addEventListener('click',()=>{const c=document.getElementById(b.dataset.clear);pads[b.dataset.clear].clearRect(0,0,c.width,c.height)})});
function drawImage(canvasId,dataUrl){if(!dataUrl)return;const img=new Image();img.onload=()=>{const c=document.getElementById(canvasId),ctx=c.getContext('2d');ctx.clearRect(0,0,c.width,c.height);ctx.drawImage(img,0,0,c.width,c.height)};img.src=dataUrl}
function compressedSignature(canvasId){const src=document.getElementById(canvasId),small=document.createElement('canvas');small.width=350;small.height=95;small.getContext('2d').drawImage(src,0,0,350,95);return small.toDataURL('image/png')}

function ensureStatusBanner(){let el=document.querySelector('#leaseSharedStatus');if(el)return el;el=document.createElement('div');el.id='leaseSharedStatus';el.style.cssText='margin:0 0 18px;padding:14px 16px;border-radius:10px;background:#eef5f0;border:1px solid #cfe0d4;color:#17382d;font-weight:700';document.querySelector('.lease-intro')?.insertAdjacentElement('afterend',el);return el}
function setLeaseStatus(status){const el=ensureStatusBanner();const map={'Not started':'Lease not started','Draft':'Draft · not yet signed','Tenant signed':'Tenant signed · awaiting landlord signature','Fully signed':'Fully signed by tenant and landlord'};el.textContent=map[status]||status||'Lease not started';const pill=document.querySelector('.draft-pill');if(pill)pill.textContent=map[status]||status||'Draft'}
function lockTenantForm(){form.querySelectorAll('input,textarea,select').forEach(el=>{if(el.name==='landlordSignature')el.disabled=true;else el.disabled=true});document.querySelectorAll('[data-clear]').forEach(b=>b.disabled=true);document.getElementById('saveDraft').disabled=true;document.querySelector('#submitLeaseShared')?.setAttribute('disabled','true')}
function applyLease(lease){remoteLease=lease||null;if(!lease)return;const data=lease.form||{};Object.entries(data).forEach(([k,v])=>setField(k,v));if(lease.tenantSignature)drawImage('tenantCanvas',lease.tenantSignature);if(lease.landlordSignature)drawImage('landlordCanvas',lease.landlordSignature);if(lease.status==='Fully signed'&&lease.landlordSignedBy)setField('landlordSignature',lease.landlordSignedBy);setLeaseStatus(lease.status||'Not started');if(lease.status==='Tenant signed'||lease.status==='Fully signed')lockTenantForm();if(statusEl){if(lease.status==='Tenant signed')statusEl.textContent='Your lease is shared with the landlord and is waiting for their signature.';else if(lease.status==='Fully signed')statusEl.textContent='Lease complete. Both parties have signed.';else statusEl.textContent='This draft is shared with the property team.'}}
async function loadRemoteLease(){if(!tenantSession.email||!(tenantSession.tenantId||tenantSession.id))return;try{const r=await jsonp({action:'tenant.getLease',email:tenantSession.email,tenantId:tenantSession.tenantId||tenantSession.id});if(r?.ok===false)throw new Error(r.error);applyLease(r.lease)}catch(e){console.error('Unable to load shared lease',e);setLeaseStatus('Draft');if(statusEl)statusEl.textContent='Shared lease could not be loaded right now. You can continue working locally.'}}

async function saveSharedDraft(showMessage=true){const data=formDataObject();localStorage.setItem('hlonyaneLeaseDraft',JSON.stringify(data));if(remoteLease?.status==='Tenant signed'||remoteLease?.status==='Fully signed')return;if(showMessage&&statusEl)statusEl.textContent='Saving shared draft…';try{await postLease('tenant.saveLeaseDraft',{form:data});setTimeout(loadRemoteLease,900);if(showMessage&&statusEl)statusEl.textContent='Draft saved to the shared lease.'}catch(e){if(statusEl)statusEl.textContent='Unable to save shared draft right now.'}}
document.getElementById('saveDraft').addEventListener('click',()=>saveSharedDraft(true));form.addEventListener('input',()=>{if(remoteLease?.status==='Tenant signed'||remoteLease?.status==='Fully signed')return;clearTimeout(window.leaseTimer);window.leaseTimer=setTimeout(()=>saveSharedDraft(false),1200)});

const submit=document.createElement('button');submit.id='submitLeaseShared';submit.type='button';submit.className='gold-btn';submit.textContent='Sign & send to landlord';document.querySelector('.lease-actions').appendChild(submit);submit.addEventListener('click',async()=>{if(!form.reportValidity())return;const data=formDataObject();if(!data.termsAccepted){form.elements.termsAccepted.focus();return}submit.disabled=true;submit.textContent='Submitting…';if(statusEl)statusEl.textContent='Submitting signed lease to landlord…';try{await postLease('tenant.submitLease',{form:data,tenantSignature:compressedSignature('tenantCanvas')});setTimeout(loadRemoteLease,900);submit.textContent='Signed & sent';if(statusEl)statusEl.textContent='Tenant signature submitted. Awaiting landlord signature.'}catch(e){submit.disabled=false;submit.textContent='Sign & send to landlord';if(statusEl)statusEl.textContent='Unable to submit the lease right now.'}});

const oldDownload=document.getElementById('downloadLease');if(oldDownload)oldDownload.hidden=true;
const printButton=document.createElement('button');printButton.type='button';printButton.className='outline-btn';printButton.textContent='Print / save as PDF';document.querySelector('.lease-actions').insertBefore(printButton,submit);printButton.addEventListener('click',()=>{const d=formDataObject();const tenantSig=remoteLease?.tenantSignature||compressedSignature('tenantCanvas');const landlordSig=remoteLease?.landlordSignature||compressedSignature('landlordCanvas');const w=window.open('','_blank');w.document.write(`<html><head><title>Hlonyane Residential lease agreement</title><style>body{font:14px Arial;color:#13293d;max-width:800px;margin:35px auto;line-height:1.5}h1{font-size:26px;border-bottom:2px solid #b98516;padding-bottom:12px}h2{font-size:17px;margin-top:24px;color:#b98516}.grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.field{border-bottom:1px solid #ccd6da;padding:8px 0}.field b{display:block;font-size:11px;color:#748088}.sig img{width:280px;height:76px;object-fit:contain;object-position:left bottom}</style></head><body><h1>Hlonyane Residential — Lease Agreement</h1><div class="grid"><div class="field"><b>Tenant</b>${d.tenantName||''}</div><div class="field"><b>ID / Passport</b>${d.tenantId||''}</div><div class="field"><b>Email</b>${d.tenantEmail||''}</div><div class="field"><b>Mobile</b>${d.tenantMobile||''}</div><div class="field"><b>Premises</b>${d.propertyAddress||''}</div><div class="field"><b>Monthly rent</b>R${d.rent||''}</div><div class="field"><b>Deposit</b>R${d.deposit||''}</div><div class="field"><b>Lease period</b>${d.startDate||''} to ${d.endDate||''}</div></div><h2>Signatures</h2><div class="grid"><div class="sig"><b>Tenant</b><br>${d.typedSignature||''}<br>${tenantSig?`<img src="${tenantSig}">`:''}</div><div class="sig"><b>Landlord</b><br>${d.landlordSignature||remoteLease?.landlordSignedBy||''}<br>${landlordSig?`<img src="${landlordSig}">`:''}</div></div><p>Status: ${remoteLease?.status||'Draft'}</p><script>window.onload=()=>window.print()<\/script></body></html>`);w.document.close()});

loadRemoteLease();